Feature/#17 food list
GESCC/danchu pull request #23
Opened 2017-03-14 14:56 UTC by ChickenPaella

#17

Food VO 변수명을 DB랑 맞춘다고 언더바 형식으로 썼는데 다른 방법이 있으면 알려주기 바람..

2017-03-14 15:04 UTC, Genie-Youn commented
자바는 당연히 낙타..

2017-03-14 16:09 UTC, genie-youn requested changes

2017-03-14 16:09 UTC, genie-youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/ListController.java
> +
Controller 이름 ListController로 충분해? 다른 list도 존재할것같음

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/ListController.java
> +	public String getAllFoodList(HttpServletRequest req, HttpServletResponse res) throws JsonProcessingException
text/json 이 아니라 application/json 아닐까

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/ListController.java
> +
ListController가 아니라 FoodController가 되어야 할것같은데?

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/ListController.java
> +	public String getCategoryFoodList(HttpServletRequest req, HttpServletResponse res, @RequestParam("category") String category) throws JsonProcessingException
두 메소드를 합칠순 없을까 어차피 다 리스트를 반환하는 메소드인데 카테고리란 파라미터가 없으면 전부다 리턴하는거니..

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/dao/FoodListDao.java
> +}
selectFoodsList 와 selectFoodsListByCategory 이런식에 네이밍이 더 나을것 같기도..

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/view/ResultView.java
> +
이거 만들어놓고 왜 안써ㅋㅋㅋ

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Food.java
> +	private String image_main;
전부다 낙타로 바꿔주고 @JsonProperties 어노테이션 사용해주면 좋을듯

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Food.java
> +		// TODO Auto-generated constructor stub
음? 무슨 일은 하는 코드

2017-03-14 16:09 UTC, Genie-Youn commented on momuck-web/src/main/resources/mapper/food/Food_SQL.xml
> +<mapper namespace="Food">
ResultType을 한번에 모아서 alias주고 관리하는 방법이 있으니 찾아보면 좋을듯

2017-03-14 16:31 UTC, ChickenPaella commented on momuck-web/src/main/java/com/danchu/momuck/vo/Food.java
> +		// TODO Auto-generated constructor stub
이거 없으니까 NoSuchMethod 에러 뱉음

2017-03-14 16:33 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Food.java
> +		// TODO Auto-generated constructor stub
Jackson이 파싱을 못해서 그럼 밑에 파라미터 우겨넣어서 만든 생성자때문에 default생성자가 없어져서 차라리 둘다 날리는게 나을것같은데

2017-03-14 16:58 UTC, genie-youn requested changes
query xml alias 처리 해줘야 할것같음
query에 order by 시간에 걸어줘야 할것같음
limit & offset 처리 해줘야 할것같음
생성자제거

2017-03-14 16:58 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Food.java
> +	@JsonProperty("name") private String name;
두개가 같은 경우엔 안붙여줘도됑

2017-03-17 17:24 UTC, genie-youn approved these changes

2017-03-17 17:24 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/FoodController.java
> +
ObjectMapper 삭제해도 괜찮을듯

2017-03-17 17:24 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/mapper/FoodMapper.java
> +
얘가 클래스 멤버변수일 필요가 있을까?

2017-03-17 17:24 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/FoodController.java
> +			@RequestParam(value = "page") int page) throws JsonProcessingException
실수로 page에 음수를 던지면 죽어버릴것 같은데 처리가 필요할것 같음

2017-03-17 17:25 UTC, Genie-Youn commented
위에것만 수정하고 머지

2017-03-18 01:06 UTC, merged