Feature/#29 register market
GESCC/danchu pull request #34
Opened 2017-03-22 14:22 UTC by ChickenPaella

등록만 테스트 완료.

API 문서까지 체크 바람

2017-03-23 00:26 UTC, genie-youn requested changes

2017-03-23 00:26 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/RestaurantController.java
> +			return new ResultView("500", "Duplicated email or name", null);
?

2017-03-23 00:26 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/RestaurantController.java
> +	public ResultView delete(HttpServletRequest req, HttpServletResponse res, @PathVariable String restaurantName) {
@TODO로 나중에 매장 주인이랑 관리자만 삭제할 수 있는 로직 추가해야한다고 명시해줘야될듯

2017-03-23 00:26 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/dao/RestaurantDao.java
> +	Restaurant updateRestaurant(Restaurant restaurant);
기존에 Dao 들이 update랑 delete는 해당 컬럼수를 리턴하니까 그거랑 맞추는게 좋아보임

2017-03-23 00:26 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/mapper/RestaurantMapper.java
> +			sqlSessionTemplate.insert(NAMESPACE + ".insertRestaurant", restaurant);
Restaurant 테이블 name 컬럼에 uniq 걸었어?

2017-03-23 00:26 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/RestaurantService.java
> +	Restaurant selectRestaurant(int seqs);
마찬가지

2017-03-23 00:26 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Restaurant.java
> +public class Restaurant {
Validation 체크가 필요할듯 별점이라던지 핸드폰번호라던지

2017-03-23 00:26 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/RestaurantServiceImpl.java
> +	public Restaurant selectRestaurant(int seq) {
Food테이블에 seq로 긁어서 해당 음식점에 메뉴들도 담아서 돌려줘야 하지 않을까?

2017-03-23 00:31 UTC, ChickenPaella commented on momuck-web/src/main/java/com/danchu/momuck/controller/RestaurantController.java
> +			return new ResultView("500", "Duplicated email or name", null);
어 이거 뭐야 ㅋㅋㅋㅋㅋ

2017-03-23 00:35 UTC, ChickenPaella commented on momuck-web/src/main/java/com/danchu/momuck/service/RestaurantServiceImpl.java
> +	public Restaurant selectRestaurant(int seq) {
이거는 우리가 음식을 먼저 고르면 그 다음 식당페이지로 넘어가는거니까 식당 정보만 보여주면 되지않을까 싶은데 그냥 하단에 음식정보도 긁어?

2017-03-23 00:49 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/RestaurantServiceImpl.java
> +	public Restaurant selectRestaurant(int seq) {
음 그 식당페이지 넘어가면 그 식당의 다른 메뉴도 보여줘야해서 메뉴정보도 같이 있는게 필요할것 같은데 withFood 이런식으로 메소드 하나 더 만들어야할듯?

2017-03-24 17:03 UTC, ChickenPaella commented on momuck-web/src/main/resources/mapper/restaurant/Restaurant_SQL.xml
> +		ORDER BY r.created DESC
클라에서 정보 선택하도록 하면 될거 같아서 메소드를 따로 안만들고 기존 쿼리만 수정했음.
근데 결과값에서 Restaurant 테이블이랑 Food 테이블이랑 이름이 같은 컬럼이 구분이 안되는 이슈가 있음.
Restaurant의 값이 Food에 덧씌워짐... 찾아봐도 잘 모르겠어 살려줘 ㅠ

2017-03-25 03:13 UTC, genie-youn requested changes

2017-03-25 03:13 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Restaurant.java
> +     */
복붙할땐 인덴트를 확인합시다

2017-03-25 03:13 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Restaurant.java
> +	private String avgScore;
String 인데 Min Max가 가능해? 테스트 해봤어?

2017-03-25 03:13 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/vo/Restaurant.java
> +	private String avgScore;
score가 float인데 얘가 String인 이유는?

2017-03-25 03:13 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/RestaurantController.java
> +		if (result == null) {
얘가 null 될 가능성은 duplicatedException을 잡아서 나왔을 경우니 그에 맞는 에러메세지가 필요해보임

2017-03-25 03:13 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/mapper/RestaurantMapper.java
> +			return sqlSessionTemplate.insert(NAMESPACE + ".updateRestaurant", restaurant);
인덴트이상함

2017-03-25 03:13 UTC, Genie-Youn commented on momuck-web/src/main/resources/mapper/restaurant/Restaurant_SQL.xml
> +		ORDER BY r.created DESC
resultMap이 restaurant니까?
이건 그거 두개 조인한 VO를 따로 만들어서 as로 컬럼명 바꾼뒤 맵핑하면 될듯

2017-03-25 03:13 UTC, Genie-Youn commented on momuck-web/src/test/java/com/danchu/momuck/controller/RestaurantControllerTest.java
> +	@Test
JUnit에서 병렬처리되서 select가 insert보다 나중에 처리된단 보장이 없음
순서를 주고싶으면 @FixMethodOrder 를 참고

2017-03-27 02:00 UTC, genie-youn approved these changes

2017-03-27 02:00 UTC, Genie-Youn commented on momuck-web/src/test/java/com/danchu/momuck/controller/RestaurantControllerTest.java
> +@FixMethodOrder(MethodSorters.DEFAULT)
NAME 으로 변경

2017-03-27 12:48 UTC, merged

2017-03-27 12:49 UTC, ChickenPaella commented
음식 추가 기능 생기면 테스트 새로 해줘야됨