#39 verify email
GESCC/danchu pull request #40
Opened 2017-03-24 20:37 UTC by jjeongg94

2017-03-25 03:28 UTC, genie-youn requested changes
나가봐야되서 일단 이정도만 수정해줘ㅋㅋ 갔다와서 자세히 볼께

우는소리하더니 잘했네

2017-03-25 03:28 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/AccountController.java
> +        	if(account.isVerify() != 1)
중괄호를 안쓰고 싶으면 한줄로 나열하고 그게 아니면 중괄호를 써주는게 가독성에 좋을듯

2017-03-25 03:28 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/AccountController.java
>  import javax.servlet.http.HttpServletRequest;
컨트롤러에 얘네가 임폴트 될 필요가?

2017-03-25 03:28 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +    private static final String AES256KEY = "aes-256-momuck-key";
Secret key는 config로 분리해서 따로 관리

2017-03-25 03:28 UTC, Genie-Youn commented on momuck-web/src/main/resources/root-context.xml
> +	<bean id="mailSender" class="org.springframework.mail.javamail.JavaMailSenderImpl">
root-context에 때려넣지말고 별도 context로 분리하고 import해줘

2017-03-25 03:28 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +		} catch (Exception e) {
해결못할거면 그냥 runtime으로 싸서 죽어버리는것도 방법

2017-03-25 03:28 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +		} catch (Exception e) {
마찬가지

2017-03-25 22:30 UTC, jjeongg94 commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +    private static final String AES256KEY = "aes-256-momuck-key";
@value 쓰는겨?????

2017-03-27 02:10 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +    private static final String AES256KEY = "aes-256-momuck-key";
웅ㅋㅋ

2017-03-27 10:35 UTC, genie-youn approved these changes
일단 머지 후 리팩터링

2017-03-27 10:35 UTC, Genie-Youn commented on momuck-web/src/main/resources/servlet-context.xml
> +
얘도 인덴트

2017-03-27 10:35 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +	@Value("#{config['aes256Key']}")
코드 인덴트

2017-03-27 10:35 UTC, merged