reset password
GESCC/danchu pull request #54
Opened 2017-04-01 08:54 UTC by jjeongg94

우선 내 이메일로 했는데
이메일 어떻게 받아와야해??

2017-04-02 10:42 UTC, genie-youn requested changes
테스트케이스 작성해줘
이메일은 requestbody로 받아오자

2017-04-02 10:42 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/AccountController.java
> +    	String email = "lalala3423@hanmail.net";
RequestBody로 받아오면 될것 같아

2017-04-02 10:42 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/AccountController.java
> +    	int result = accountService.updatePassword(account);
나중에 비밀번호 변경기능이 있을것 같으니 얘도 resetPassword로 바꾸는게 좋을듯

2017-04-02 10:42 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/AccountController.java
> +    	int result = accountService.updatePassword(account);
파라미터가 굳이 account일 필요 없이 String email 넘겨줘도 될듯

2017-04-02 10:42 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/controller/AccountController.java
> +    		return new ResultView("500", "Server Internal Error", null);
생길수 있는 예외가 뭐가 있을까 해당하는 이메일이 없거나 디비에러거나 일단 생각나는건 그 두가진데 더 고민해 보는것도 좋을듯

2017-04-02 10:42 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +		} catch (Exception e) {
얘도 messagingException으로 바꿔주면 좋을듯?

2017-04-02 10:42 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +	public int updatePassword(Account account) {
해당 Account가 실제로 존재하는지 찾는 로직이 추가되어야 할듯

2017-04-03 01:49 UTC, ChickenPaella commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +		MimeMessageHelper helper;
Service에 sendEmail 등록 안되어있는거 같아

2017-04-03 06:27 UTC, jjeongg94 commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +		} catch (Exception e) {
얘 messagingException 아니구 다른 exeption 7개 있는데 각각 다 처리해줘야 하는거야?

2017-04-03 07:00 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/service/AccountServiceImpl.java
> +		} catch (Exception e) {
헐ㅋㅋㅋ일단 냅두는걸로

2017-04-11 11:34 UTC, genie-youn approved these changes

2017-04-11 11:34 UTC, merged