Add Foods register & delete
GESCC/danchu pull request #65
Opened 2017-04-05 06:32 UTC by ChickenPaella

메뉴 등록, 삭제 기능 추가

2017-04-06 07:28 UTC, genie-youn requested changes
코멘트 확인

2017-04-06 07:28 UTC, Genie-Youn commented on momuck-web/src/main/java/com/danchu/momuck/mapper/FoodMapper.java
> +	public Food insertFood(Food food) {
name에 uniq 걸어뒀어? 그런데 메뉴명이 같은 가능성이 전혀 없나?

2017-04-07 13:52 UTC, ChickenPaella commented on momuck-web/src/main/java/com/danchu/momuck/mapper/FoodMapper.java
> +	public Food insertFood(Food food) {
uniq 걸려있어. 그리고 메뉴명이 겹치는 경우는 없을거 같은데... 사이즈 같은건 이름에 같이 표기해줘야겠지

2017-04-08 14:03 UTC, ChickenPaella commented
아무나 읽고 리뷰해주세여..

2017-04-09 05:45 UTC, genie-youn approved these changes
잘했겠지머 헤헤

2017-04-09 05:46 UTC, merged